name: Fifth Workflow
on: [push, issues, pull_request]

jobs:
  run-first-command:
    runs-on: ubuntu-latest
    steps:
      - name: Display some Text
        run: echo "Some text"
      - name: Command in Multiline
        run: |
          echo $GITHUB_SHA
          echo $GITHUB_REF
