
name: First Workflow
on: [push]

jobs:
  run-first-command:
    runs-on: ubuntu-latest
    steps:
      - name: Display some Text
        run: echo "Some text"
      - name: List Files
        run: |
          ls -a
      - uses: actions/checkout@v4
      - name: List Fil
         run: ls -a
