# Используем официальный образ Nginx
FROM nginx:latest

# Копируем файл конфигурации Nginx
COPY nginx.conf /etc/nginx/nginx.conf

# Копируем HTML-файлы в директорию Nginx
COPY html/ /usr/share/nginx/html/
